### ISSUE TITLE
Exclusively use CMake as the build system

### ISSUE THREAD

**Issue by rs22** [Railway-CCS/rasta-protocol#4]
Currently, there are two build systems in this project: Gradle (which is common in the Java world) and CMake, which (from my personal observations) is more familiar to C/C++ programmers.

I'd therefore propose to migrate to CMake and remove the Gradle project files.
The following features, however, are not yet available from CMake: 

 - [x] CUnit tests
 - [x] Static code analysis (cppcheck)
 - [x] Memory leak checker (valgrind)
 - [ ] Code coverage checking (lcov)
 - [x] Documentation generator (doxygen)

**Comment by rs22** [comment]
If that integration with CMake exists, I'd vote to make use of it.

**Comment by a-andre** [comment]
With #8 memory leak checking also works (`ctest -T memcheck`). #10 adds the missing valgrind options that are used by build.gradle.
